# Generated by Django 5.1.4 on 2025-02-02 11:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=tinymce.models.HTMLField(),
        ),
    ]
